### PR TITLE
Display received essences

### PR DESCRIPTION
**Pull request by aramunn**
Shows a pop-up when essences are gained.

Hold off on merging for now. I want to have it running a bit more to make sure nothing got missed in the porting.

### CODE REVIEW

**Comment by Mischh** [comment]
Hey Aramunn!

I really love seeing people being interested in this Addon, having people bringing Ideas and requesting stuff.
Firstly, you got a invite to collaborate. Its basically just so you can merge your stuff yourself.
Secondly... I have a 'small' problem with this request. Its a time-wise 99% empty undescriptive black box. Don't get me wrong, the Idea is really good, be prepared tho: I'll probably change its appearance alot.

These were the Ideas i had, as Zod mentioned it the first time to me (Sorry German Client):
Ideas
Because the third picture isn't very descriptive, have some code:
`Event_FireGenericEvent("StoryPanelDialog_Show", GameLib.CodeEnumStoryPanel.Default, {"Maybe here?","523 Red Essences"}, 6) `

Sorry :(
-Mischh

**Comment by Zod-** [comment]
Aramunns first idea was it to use existing loot stack display too (your first pic). There are a few problems with that so after discussing it a bit we decided it was too much hassle to make and having a simple display was just the easiest solution. 

You could fake an item and fire the loot event manually. I just don't like the idea of faking the item because it will break eventually. I don't think we can reliably fake all of the methods and ensure that the addons subscribing to these events don't break. There are  4 carbine addons using the event and who knows how many 3rd party ones.

I don't see myself using the one in your second pic. I want the display to be separate of the tracker since I wouldn't be able to see my gained essence when it is hidden like in raids.
The last one looks a bit too dull for me.

**Comment by aramunn** [comment]
Hi Mischh,

No problem :). I expect it will change a bit before merging. This is just where I left off on PrimalTracker.

Is the empty box the only issue you have with this? That empty box will go away when you lock it in the Interface Options menu. I'm thinking I'll change it so the background will only show up when the mouse is over it and it's unlocked. That way it can stay unlocked but won't be distracting with the background.

Also I don't like the fact that when you only get purple it shows up way on the right by itself. I was trying to find a better way to do that. Maybe a horizontal stack that expands to the right. So when you only get one type it'll always show up in the same location no mater the color.

I'll wait to make those change until we decide the best way to show essence gains. Ideally I'd like it to be like your first picture, but we'd need to get around the issues Zod raised first.

**Comment by Mischh** [comment]
Okay, I'll go a little deeper into my reasons disliking the CURRENT solution (you mentioned fixes to some, these are specifically excluded) - I do not expect all of these to be fixed, some of them are very hard to get right:
A) 99% of time no information - people will ask for ways to simple remove that feature, because it just has no place in an interface for most of its time. People will not get what its for, because it only does stuff in the most intense situation this game has to offer: 'End of Bossfight'

B) Where does it come from? - Most addons are only installed for a single reason, not because its full package is required. This is very closely bound to A), but because its empty most of the time, people will get frustrated figuring out which addon would add a black movable box. (not the best advertisement for an addon xP)

C) It needs a location - The default position should not be overlapped by stuff in general. It should pop up in a location thats expectable. Either the user needs to choose this position by themselves (for this 'B)' is important), or it should be a game-defined location.

NONE of my pictures solve all three problems. And all of them have their own problems:
Pic 1) fixes A) & C), but B) is a big problem. Also, I do not like supporting stuff, I'll never use (I have this addon deactivated in my own interface) - Zod's problem isn't really a thing in my opinion.. if it were the perfect position, i would hack my way into it. (I think, i wouldnt fire the Event, i would sepcifically call the function handling the event, to remove alot of the potential problems)

Pic 2) fixes A) & B), but its not really the right location to pop up rewards. Still this is my favorite, because of it fixing B) - I'm very sorry Zod, but 'I cant see, because I hide' is a VERY personal problem. (this is true for my problem with 1) aswell.)

Pic 3) fixes A) and is only included, because its the solution, i gave my guildmembers on patchday. It's the one thats unsuitable almost every way.

Lastly, I want to add another Option: Fix A) & C) (and partially B) the other way around, by filling it with Information. Have it always display the current amount of available Essences, only expanding vertically for newly entering ones. (sorry paint - ignore numbers inside icons) Pic 4:
Pic 4)

-Mischh

**Comment by aramunn** [comment]
Zod and I discussed that last option you presented but decided other addons take care of showing totals (E.g. CurrencyCount). Also I personally want the essence display to be in the middle of the screen so I see it and don't have to remember to look to the edge of the screen when I kill things. If the box was always showing data I would need to move it off to the side.

Maybe we should have a few options for the user to choose from in how the essence gains are displayed. Like Pic 1, Pic 2, and the new option with the totals. We could have a dropdown selection in the bonus rewards tab of the content finder. Doing multiple would be more work though.

**Comment by Zod-** [comment]
I don't think hiding it is a personal problem. The default loot stack addon already shows your gained cash somewhere in the bottom-left on your screen http://i.imgur.com/5CkkXwe.png. Other 3rd party addons show cash/glory in a similiar fashion http://i.imgur.com/WO9zpml.png. I just want a similiar display for the essences and we just used our own display because it was way easier. The ideal solution would be to add it to those existing displays but modifying other addons is always annyoing.

We can just make this whole thing into a separate addon if you don't like it.

**Comment by Mischh** [comment]
Zod: Because of reasons stated in B), i would prefer your last suggestion. I will support that of course, but 'B)' is very important for me. 
Aramunns Suggestion is also something, i would be fine with, as long as Pic2 ist the Default.

As you both probably saw, i created a branch, which will depending on the solution be kept unmerged.

-Mischh

**Pull request closed without merging**
